driver:
  name: ec2

provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2
    driver:
      image_id: ami-1441c367
      instance_type: t2.medium

suites:
  - name: appveyor-deploy-3-12-0
    run_list:
      - recipe[appveyor-deploy-3-12-0::default]
    attributes:
      access_key: <%= ENV['ENVIRONMENT_ACCESS_KEY'] %>
