driver:
  name: ec2

provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2
    driver:
      image_id: ami-1441c367
      instance_type: t2.medium

suites:
  - name: appveyor-agent-3-12-0
    run_list:
      - recipe[appveyor-agent-3-12-0::default]
    attributes:
      environment_access_key: <%= ENV['ENVIRONMENT_ACCESS_KEY'] %>
  - name: appveyor-agent-latest
    run_list:
      - recipe[appveyor-agent-latest::default]
    attributes:
      environment_access_key: <%= ENV['ENVIRONMENT_ACCESS_KEY'] %>
  - name: appveyor-deploy
    run_list:
      - recipe[appveyor-deploy::default]
    attributes:
      api_token: <%= ENV['API_TOKEN'] %>
      environment_access_key: <%= ENV['ENVIRONMENT_ACCESS_KEY'] %>
      environment_name: <%= ENV['ENV_NAME'] %>
      project_slug: <%= ENV['PROJECT_SLUG'] %>
      account_name: <%= ENV['ACCOUNT_NAME'] %>
