driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2

suites:
  - name: appveyor-deploy
    run_list:
      - recipe[appveyorapi::default]
    attributes:
      api_token: <%= ENV['API_TOKEN'] %>
      environment_access_key: <%= ENV['ENVIRONMENT_ACCESS_KEY'] %>
      name: <%= ENV['ENV_NAME'] %>
      project: <%= ENV['PROJECT'] %>
      account: <%= ENV['ACCOUNT'] %>
