
os: Windows Server 2012 R2
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_pass: Pass@word1
  winrm_port: 5985
  KITCHEN_YAML: c:\projects\appveyorapi\.kitchen.appveyor.yml
  SSL_CERT_FILE: c:\projects\appveyorapi\certs.pem
  project_name: test
  environment_name: test-production
  buildversion: 1.0.2
  deployment_group: test
  account: Gopi
  access_key:
    secure: dCESKEbzxmx6H1VF+jjQWq7iQB9vLGqCk6fI+7n2Jbg=
  api_token:
    secure: nuPpGlCRkHII619xXl4GV54xwhKPxAFDweCWF6waC4Q=

  matrix:
    - ruby_version: "21"

clone_folder: c:\projects\appveyorapi
clone_depth: 1
branches:
  only:
    - master

install:
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: Write-Host $env:PATH
  - ps: ruby --version
  - ps: gem --version
  - ps: gem install bundler --quiet --no-ri --no-rdoc
  - ps: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\appveyorapi\certs.pem
  - ps: bundler --version

build_script:
  - bundle install

test_script:
  - bundle exec rake style
  - bundle exec kitchen verify

after_build:
  - berks package appveyorapi.tar.gz
  - appveyor PushArtifact appveyorapi.tar.gz -FileName appveyorapi-%appveyor_build_version%.tar.gz -DeploymentName appveyorapi
